version: '3'
services:
  db:
      build: "1_ETL/4_postgres/."
      image: "127.0.0.1:5000/treeful_db:0.0.2"
      ports:
        - "5432:5432"
      secrets:
        - postgres_pw
      environment:
        POSTGRES_DB: treeful-test
        POSTGRES_PW_FILE: /run/secrets/postgres_pw
        PGDATA: /var/lib/postgresql/data/pgdata
      volumes:
        -
          type: bind
          source: ./1_ETL/4_postgres
          target: /var/lib/postgresql/data
      deploy:
        resources:
            limits:
              cpus: '4'
              memory: 8096M
            reservations:
              cpus: '2'
              memory: 1024M
  frontend:
    build:
      context: "./3_shiny_frontend/"
      secrets:
          - postgres_pw
          - postgres_host
    image: "127.0.0.1:5000/treeful_frontend:0.0.2"
    volumes:
      - ./1_ETL/2_Data/1_output/tree_profiles:/srv/shiny-server/treeful/insta/app/tree_profiles
      - ./1_ETL/2_Data/0_raw_data:/srv/shiny-server/treeful/data
    ports:
      - "8080:3838"
    secrets:
      - postgres_pw
      - postgres_host
    environment:
      POSTGRES_DB: treeful-test
      POSTGRES_PW_FILE: /run/secrets/postgres_pw
      POSTGRES_HOST_FILE: /run/secrets/postgres_host
    deploy:
      resources:
          limits:
            cpus: '2'
            memory: 4096M
          reservations:
            cpus: '1'
            memory: 1024M
      # restart_policy:
      #   condition: on-failure
      #   delay: 5s
      #   max_attempts: 3
      #   window: 120s

  # etl:
  #   # building container to fetch tree dbs and raster data and stick into postgres
  #   build: 1_ETL/
  #   image: treeful_etl
  #   volumes:
  #     - .:/home/rstudio
  #   secrets:
  #     - postgres_pw
  #     - postgres_host
  #     - copernicus_key
  #     - copernicus_uid
  #     - gbif_email
  #     - gbif_pw
  #     - gbif_uid
  #     - keyring_pw
secrets:
      postgres_pw:
        file: ./1_ETL/0_secrets/postgres_pw.txt
      postgres_host:
        file: ./1_ETL/0_secrets/postgres_host.txt
      copernicus_key:
        file: ./1_ETL/0_secrets/copernicus_key.txt
      copernicus_uid:
        file: ./1_ETL/0_secrets/copernicus_uid.txt
      gbif_email:
        file: ./1_ETL/0_secrets/gbif_email.txt
      gbif_pw:
        file: ./1_ETL/0_secrets/gbif_pw.txt
      gbif_uid:
        file: ./1_ETL/0_secrets/gbif_uid.txt
      keyring_pw:
        file: ./1_ETL/0_secrets/keyring_pw.txt
