version: '3'
services:
  db:
  # need to figure from official docs how wxactly to enable raster extension
      build: "4_postgres/."
      image: "postgis/postgis"
      ports:
        - "5432:5432"
      secrets:
        - postgres_pw

  etl:
    # building container to fetch tree dbs and raster data and stick into postgres
    build: ./
    volumes:
      - ./3_R:/code
    secrets: 
      - postgres_pw
      - copernicus_key
      - copernicus_uid
      - gbif_email
      - gbif_pw
      - gbif_uid
secrets:
      postgres_pw:
        file: ./postgres_pw.txt
      copernicus_key:
        file: ./copernicus_key.txt
      copernicus_uid:
        file: ./copernicus_uid.txt
      gbif_email:
        file: ./gbif_email.txt
      gbif_pw:
        file: ./gbif_pw.txt
      gbif_uid:
        file: ./gbif_uid.txt
      