version: '3'
services:
  db:
  # need to figure from official docs how wxactly to enable raster extension
      build: "4_postgres/."
      #image: "postgis/postgis"
      ports:
        - "5432:5432"
      secrets:
        - postgres_pw
      environment:
        POSTGRES_DB: treeful-test
        POSTGRES_PASSWORD_FILE: /run/secrets/postgres_pw
        PGDATA: /var/lib/postgresql/data/pgdata
      volumes:
        -
          type: bind
          source: ./4_postgres
          target: /var/lib/postgresql/data

  etl:
    # building container to fetch tree dbs and raster data and stick into postgres
    build: ./
    volumes:
      - .:/home/rstudio
    secrets: 
      - postgres_pw
      - copernicus_key
      - copernicus_uid
      - gbif_email
      - gbif_pw
      - gbif_uid
      - keyring_pw
secrets:
      postgres_pw:
        file: ./0_secrets/postgres_pw.txt
      copernicus_key:
        file: ./0_secrets/copernicus_key.txt
      copernicus_uid:
        file: ./0_secrets/copernicus_uid.txt
      gbif_email:
        file: ./0_secrets/gbif_email.txt
      gbif_pw:
        file: ./0_secrets/gbif_pw.txt
      gbif_uid:
        file: ./0_secrets/gbif_uid.txt
      keyring_pw:
        file: ./0_secrets/keyring_pw.txt
      